function divText = GetSlidyDivText(slideTitle,text)

divText = ['<div class="slide">\n' ...
            '<center>\n'...
            ['<h3>' slideTitle '</h3>\n'] ...
                ['<div style="width:100%%;">\n'] ...
                    '<center>\n' ...
                    [text] ...		  
                    '</center>\n' ...
                '</div>\n' ...
            '</center>\n' ...
            '</div>\n'];