function Print2Slidy(fileName,coverText,firstSlideText,body)

fileName = [fileName '.html'];
fileID = fopen(fileName,'w');

slidyHeader = ['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN " \n'...
 '"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n'...
 ' <html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">\n'... 
 '<head>\n'...
 '<title>RESULTADOS</title>\n'...
'<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n' ...
'<meta name="font-size-adjustment" content="-2" />\n' ...
'<link rel="stylesheet" href="styles/slidy.css" type="text/css" />\n' ...
'<link rel="stylesheet" href="styles/w3c-blue.css" type="text/css" />\n' ...
'<link rel="stylesheet" href="exploratoryCss.css" type="text/css" />\n' ...
'<script src="scripts/slidy.js" charset="utf-8" type="text/javascript">\n' ...
'</script>\n' ...
'</head>\n' ...
'<body>\n' ...
'<img src="Ineco/lpen.jpg" />\n' ...
'</div>\n' ...
'<div class="slide cover title">\n' ...
['<h1>' coverText '</h1>\n'] ...
'</div>\n' ...
'<div class="slide">\n' ...
'<center><br><br>\n' ...
['<h2>' firstSlideText '\n'] ...
'</h2>' ...
'</center>\n' ...
'</div>\n'] ;

slidyFooter = ['</body>\n'...
'</html>'];

completeSlidy = [slidyHeader body slidyFooter];

fprintf(fileID,'%s \n',sprintf(completeSlidy));
fclose(fileID);
