clear,
clc
direc = 'C:\AnalisisEEG\Alzheimer_colombia';
cd(direc)
ConvertLocations ('Channel_Locations_64chnsCol.ced', 'coordsNeuroscan.csd' )
E = {...
    'FP1'...
    'FPZ'...'...
    'FP2'...
    'AF3'...
    'AF4'...
    'F7'...
    'F5'...
    'F3'...
    'F1'...
    'FZ'...
    'F2'...
    'F4'...
    'F6'...
    'F8'...
    'FT7'...
    'FC5'...
    'FC3'...
    'FC1'...
    'FCZ'...
    'FC2'...
    'FC4'...
    'FC6'...
    'FT8'...
    'T7'...
    'C5'...
    'C3'...
    'C1'...
    'CZ'...
    'C2'...
    'C4'...
    'C6'...
    'T8'...
    ...'HEO'...
    'TP7'...
    'CP5'...
    'CP3'...
    'CP1'...
    'CPZ'...
    'CP2'...
    'CP4'...
    'CP6'...
    'TP8'...
    ...'VEO'...
    'P7'...
    'P5'...
    'P3'...
    'P1'...
    'PZ'...
    'P2'...
    'P4'...
    'P6'...
    'P8'...
    'PO7'...
    'PO5'...
    'PO3'...
    'POZ'...
    'PO4'...
    'PO6'...
    'PO8'...
    ...'CB1'...
    'O1'...
    'OZ'...
    'O2'...
    ...'CB2'
    };

E = E';
M = ExtractMontage('coordsNeuroscan.csd',E);
MapMontage(M);
%%
% ------------ Step 3 -----------------------------------------------------
tic
[G,H] = GetGH(M);
toc
% ------------ Step 4 -----------------------------------------------------
% D = textread('NR_C66_trr.dat');D = D'; channel x tiempo

grupo = {'MP_ALZ_C','MP_ALZ_P'};

conds1 = {'REP','SS2','SS3'};
conds2 = {'EEG','SS2','SS3'};

% matlabpool(3)
sujs = {'001','002','003','004','005','006','007','008','009','010'};
for pac = 1:2
    sujetos = grupo{pac};
    for i = 1:10
        for cond = 1:3
            if i==1 && cond==1, continue,end
            disp(['leyendo sujeto ', grupo{pac}(4:end),' sujeto ', num2str(i),' cond ',num2str(cond)])
            
            cd(fullfile(direc,'data','set_epochs_trialandICArejected'))
            load([sujetos,sujs{i},'_',conds2{cond},'_ICArejected.mat']);
            Y = [];
            for ep = 1:size(data,3)
                temp = CSD (data(:,:,ep), G, H);
                Y = cat(3,Y,temp);
            end
            data = Y;
            
            save([sujetos,sujs{i},'_',conds2{cond},'_ICArejectedCSD.mat'],'data');
            
        end
    end
end